- name: setup EPEL repository
  yum:
    name=epel-release
    state=latest

- name: install dnf
  yum: >
    name=dnf
    state=latest

- name: upgrade all packages
  dnf: >
    name=*
    state=latest
